### ISSUE TITLE
Missing CoC and so...

### ISSUE THREAD

**Issue by gmesika-coti** [coti-io/confidentiality-contracts#15]
@danielgruesso kindly add it here also as in https://github.com/coti-io/coti-sdk-typescript-examples/pull/8

**Comment by danielgruesso** [comment]
@gmesika-coti see https://github.com/coti-io/confidentiality-contracts/pull/16

**Comment by gmesika-coti** [comment]
plz fix the links
![image](https://github.com/user-attachments/assets/59dbe76e-bbb2-4fa9-8c62-537e10f412c9)
