### ISSUE TITLE
JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)

### ISSUE THREAD

**Issue by Gessi12** [coti-io/confidentiality-contracts#22]
When I conducted yarn test-erc20

![image](https://github.com/user-attachments/assets/cd27e7a3-9bf4-4b3f-9efc-e6555c76708c)

This is hardhat.config.ts
![image](https://github.com/user-attachments/assets/98c45cd7-b11d-44f7-90de-ef522b60298a)

**Comment by gmesika-coti** [comment]
@eitanz-coti kindly check

**Comment by eitanz-coti** [comment]
Hi @Gessi12 ,

can you please confirm that you fetched the latest version tag v1.0.0 and also that you reinstall the yarn package ?

**Comment by Gessi12** [comment]
> Hi @Gessi12 ,
> 
> can you please confirm that you fetched the latest version tag v1.0.0 and also that you reinstall the yarn package ?

yes

![image](https://github.com/user-attachments/assets/b3443695-209e-4d43-aefe-aedd9500fc54)

**Comment by eitanz-coti** [comment]
Hi @Gessi12 , thanks again for answering. 
could you please try to delete node_modules , artifacts and cache direcotries and try agin ?

**Comment by Gessi12** [comment]
> Hi @Gessi12 , thanks again for answering. could you please try to delete node_modules , artifacts and cache direcotries and try agin ?

It's useless, the same prompt still applies

**Comment by Gessi12** [comment]
I don't know if there is a problem with testnet, as my account is also unable to make transfers and has been pending
![image](https://github.com/user-attachments/assets/04de05fd-292b-4406-b05c-21db942e3781)

**Comment by eitanz-coti** [comment]
Hi @Gessi12 
please verify the correct RPC url was added to metamask - https://testnet.coti.io/rpc. 

if the url is correct please try to see that the correct nonce is been set, it can be retrived by running the below in some trminal: 
curl https://testnet.coti.io/rpc \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getTransactionCount","params":["0xcA4322401c97C0AFAcD274aC38DbE1bDE5aABCda", "latest"],"id":1,"jsonrpc":"2.0"}'
  
  {"jsonrpc":"2.0","id":1,"result":"0x15f"} --> the result is in Hex and need to be convert to decimal. 

* if you need example for python or node js please let me know . 


regarding the  test-erc20, i faced this issue when node_modules was not deleted when moving to testnet version > 1.0.0. 
can you please everything from scratch including delete of node_modules, artifacts and cache directories.

**Comment by Gessi12** [comment]
> * example

yes, I need example for python or node js

**Comment by Gessi12** [comment]
> Hi @Gessi12 please verify the correct RPC url was added to metamask - https://testnet.coti.io/rpc.
> 
> if the url is correct please try to see that the correct nonce is been set, it can be retrived by running the below in some trminal: curl https://testnet.coti.io/rpc -X POST -H "Content-Type: application/json" --data '{"method":"eth_getTransactionCount","params":["0xcA4322401c97C0AFAcD274aC38DbE1bDE5aABCda", "latest"],"id":1,"jsonrpc":"2.0"}'
> 
> {"jsonrpc":"2.0","id":1,"result":"0x15f"} --> the result is in Hex and need to be convert to decimal.
> 
> * if you need example for python or node js please let me know .
> 
> regarding the test-erc20, i faced this issue when node_modules was not deleted when moving to testnet version > 1.0.0. can you please everything from scratch including delete of node_modules, artifacts and cache directories.

![image](https://github.com/user-attachments/assets/3beca576-dc9e-4daa-aede-fd679c2a0bf2)
RPC url is right, but it still prompts a JSON-RPC error.

yes, I need example.

**Comment by Gessi12** [comment]
@eitanz-coti bash: curl https://testnet.coti.io/rpc: No such file or directory

**Comment by Gessi12** [comment]
@eitanz-coti 
![image](https://github.com/user-attachments/assets/19733ff6-7c37-4d47-914b-728ee892812f)
Latest version

**Comment by manxiaqu** [comment]
@eitanz-coti
Same problem when using `yarn test-erc20`,  I have checed to the tag v1.0.0. it seems some problem when connect to `testnet.coti.io`, my rpc url is `const provider = initEtherProvider('https://testnet.coti.io/rpc')`, also i have test it using cmd `curl https://testnet.coti.io/rpc -X POST -H "Content-Type: application/json" --data '{"method":"eth_getTransactionCount","params":["0x48f4BDb54c5802194024dCe5fA7B1d8443CB7aA1", "latest"],"id":1,"jsonrpc":"2.0"}'`
But all failed with error `curl: (28) Failed to connect to testnet.coti.io port 443: Operation timed out` or `JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)`

**Comment by Gessi12** [comment]
> @eitanz-coti Same problem when using `yarn test-erc20`, I have checed to the tag v1.0.0. it seems some problem when connect to `testnet.coti.io`, my rpc url is `const provider = initEtherProvider('https://testnet.coti.io/rpc')`, also i have test it using cmd `curl https://testnet.coti.io/rpc -X POST -H "Content-Type: application/json" --data '{"method":"eth_getTransactionCount","params":["0x48f4BDb54c5802194024dCe5fA7B1d8443CB7aA1", "latest"],"id":1,"jsonrpc":"2.0"}'` But all failed with error `curl: (28) Failed to connect to testnet.coti.io port 443: Operation timed out` or `JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)`

@eitanz-coti Me too, no matter it's testnet or devnet. Is it an RPC issue?

**Comment by gmesika-coti** [comment]
@Gessi12 , @manxiaqu 
please use https://github.com/coti-io/confidentiality-contracts/releases/tag/1.0.3

**Comment by Gessi12** [comment]
@gmesika-coti 
curl https://testnet.coti.io/rpc
-X POST
-H "Content-Type: application/json"
--data '{"method":"eth_getTransactionCount","params":["0xcA4322401c97C0AFAcD274aC38DbE1bDE5aABCda", "latest"],"id":1,"jsonrpc":"2.0"}'

I want to use RPC to retrieve data. Is there any other RPC that can be used?

**Comment by Gessi12** [comment]
![image](https://github.com/user-attachments/assets/eed37cb9-2de6-455f-89a1-84f013a347c3)
![image](https://github.com/user-attachments/assets/317e4d97-b91d-453b-b8b5-9f071167c6aa)


> @Gessi12 , @manxiaqu please use https://github.com/coti-io/confidentiality-contracts/releases/tag/1.0.3

**Comment by manxiaqu** [comment]
I try to connect to the rpc just using ethers, but it doesn't work, here is the code:
```javascript
import { JsonRpcProvider } from "ethers";

describe("rpc test", function () {
  it("ether rpc test", async function() {
    const rpcProvider = new JsonRpcProvider("https://testnet.coti.io/rpc");
    let out = await rpcProvider.getBalance("0x48f4BDb54c5802194024dCe5fA7B1d8443CB7aA1");
    console.log(out);
  })
})

```

Is there any limit for rpc? or can you give a simple runnable code to test the connection of the rpc

**Comment by Gessi12** [comment]
> I try to connect to the rpc just using ethers, but it doesn't work, here is the code:我尝试仅使用 ethers 连接到 rpc，但它不起作用，这是代码：
> 
> ```js
> import { JsonRpcProvider } from "ethers";
> 
> describe("rpc test", function () {
>   it("ether rpc test", async function() {
>     const rpcProvider = new JsonRpcProvider("https://testnet.coti.io/rpc");
>     let out = await rpcProvider.getBalance("0x48f4BDb54c5802194024dCe5fA7B1d8443CB7aA1");
>     console.log(out);
>   })
> })
> ```
> 
> Also, I have tried with/without vpn, But it all failed.另外，我试过有/没有 vpn，但都失败了。
> 
> Is there any limit for rpc? or can you give a simple runnable code to test the connection of the rpcrpc 有限制吗？或者你能给出一个简单的 runnable 代码来测试 RPC 的连接

I also think there is a problem with RPC

**Comment by gmesika-coti** [comment]
try to replace JsonRpcProvider with getDefaultProvider

**Comment by manxiaqu** [comment]
> try to replace JsonRpcProvider with getDefaultProvider

Same error.

The logic is the same when passing the rpc url to `getDefaultProvider`, they all use `new JsonRpcProvider` to create provider

**Comment by Gessi12** [comment]
`import requests
import json

# 定义请求的URL

url = "https://testnet.coti.io/rpc"

# 定义请求头和请求数据
headers = {"Content-Type": "application/json"}
data = {
    "method": "eth_getTransactionCount",
    "params": ["0x415d6de6DD9d14b1502E3400365D4c70B0c56ad9", "latest"],
    "id": 1,
    "jsonrpc": "2.0"
}

# 发送POST请求
response = requests.post(url, headers=headers, data=json.dumps(data))

# 检查响应状态码
if response.status_code == 200:
    # 输出响应数据
    print("Response:", response.json())
else:
    print(f"Error: {response.status_code}, {response.text}")
`
I tried to use Python to retrieve data but failed

**Comment by Gessi12** [comment]
`import requests
import json

url = "https://testnet.coti.io/rpc"

headers = {"Content-Type": "application/json"}
data = {
    "method": "eth_getTransactionCount",
    "params": ["0x415d6de6DD9d14b1502E3400365D4c70B0c56ad9", "latest"],
    "id": 1,
    "jsonrpc": "2.0"
}


response = requests.post(url, headers=headers, data=json.dumps(data))

if response.status_code == 200:
    print("Response:", response.json())
else:
    print(f"Error: {response.status_code}, {response.text}")
`
I tried to use Python to retrieve data but failed

**Comment by gmesika-coti** [comment]
Please try the following code snippet and reply back with the output.
you can try also 2 other RPC endpoints

testnet-magnus-validator.coti.io
testnet-minor-validator.coti.io

`import requests
import json

import logging
import contextlib
from http.client import HTTPConnection

def debug_requests_on():
    '''Switches on logging of the requests module.'''
    HTTPConnection.debuglevel = 1

    logging.basicConfig()
    logging.getLogger().setLevel(logging.NOTSET)
    requests_log = logging.getLogger("requests.packages.urllib3")
    requests_log.setLevel(logging.NOTSET)
    requests_log.propagate = True

def debug_requests_off():
    '''Switches off logging of the requests module, might be some side-effects'''
    HTTPConnection.debuglevel = 0

    root_logger = logging.getLogger()
    root_logger.setLevel(logging.WARNING)
    root_logger.handlers = []
    requests_log = logging.getLogger("requests.packages.urllib3")
    requests_log.setLevel(logging.WARNING)
    requests_log.propagate = False

debug_requests_on()
url = "https://testnet-magnus-validator.coti.io/rpc"

headers = {"Content-Type": "application/json"}
data = {
    "method": "eth_getTransactionCount",
    "params": ["0x415d6de6DD9d14b1502E3400365D4c70B0c56ad9", "latest"],
    "id": 1,
    "jsonrpc": "2.0"
}


response = requests.post(url, headers=headers, data=json.dumps(data))

if response.status_code == 200:
    print("Response:", response.json())
else:
    print(f"Error: {response.status_code}, {response.text}")`

**Comment by Gessi12** [comment]
> Please try the following code snippet and reply back with the output.请尝试以下代码片段，并回复输出。 you can try also 2 other RPC endpoints您还可以尝试其他 2 个 RPC 端点
> 
> testnet-magnus-validator.coti.io testnet-minor-validator.coti.io
> 
> ```
> 
> import requests
> import json
> 
> import logging
> import contextlib
> from http.client import HTTPConnection
> 
> def debug_requests_on():
>     '''Switches on logging of the requests module.'''
>     HTTPConnection.debuglevel = 1
> 
>     logging.basicConfig()
>     logging.getLogger().setLevel(logging.NOTSET)
>     requests_log = logging.getLogger("requests.packages.urllib3")
>     requests_log.setLevel(logging.NOTSET)
>     requests_log.propagate = True
> 
> def debug_requests_off():
>     '''Switches off logging of the requests module, might be some side-effects'''
>     HTTPConnection.debuglevel = 0
> 
>     root_logger = logging.getLogger()
>     root_logger.setLevel(logging.WARNING)
>     root_logger.handlers = []
>     requests_log = logging.getLogger("requests.packages.urllib3")
>     requests_log.setLevel(logging.WARNING)
>     requests_log.propagate = False
> 
> debug_requests_on()
> url = "https://testnet-magnus-validator.coti.io/rpc"
> 
> headers = {"Content-Type": "application/json"}
> data = {
>     "method": "eth_getTransactionCount",
>     "params": ["0x415d6de6DD9d14b1502E3400365D4c70B0c56ad9", "latest"],
>     "id": 1,
>     "jsonrpc": "2.0"
> }
> 
> 
> response = requests.post(url, headers=headers, data=json.dumps(data))
> 
> if response.status_code == 200:
>     print("Response:", response.json())
> else:
>     print(f"Error: {response.status_code}, {response.text}")
> ```

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): testnet-magnus-validator.coti.io:443

**Comment by manxiaqu** [comment]
I test the rpc url with curl again, but it all failed, if I replace the url to ethereum Sepolia rpc url, it's ok. So I think it is the rpc's issue.
![error](https://github.com/user-attachments/assets/4c0815d6-24ed-4bfe-bf23-9db014e01003)

**Comment by gmesika-coti** [comment]
@Gessi12 is this issue still releavent?
